x-hf-cache: &hf-cache '${HF_CACHE_PATH:-${HOME}/.cache/huggingface}:/root/.cache/huggingface:cached'

services:
  database:
    container_name: books_database
    image: reinikp2/hybrid-postgres #alt: postgres:17.0 + pgvector
    restart: unless-stopped
    ports:
      - 5431:5432 # (check for conflicts wrt. host)
    environment:
      - TZ=Europe/Helsinki  # Set the timezone
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  database-migrations:
    image: flyway/flyway:10
    environment:
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=password
      - FLYWAY_URL=jdbc:postgresql://database:5432/postgres
    depends_on:
      database:
        condition: service_started
    volumes:
      - ./database-migrations:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate

  loader:
    build:
      context: .
      dockerfile: apps/loader/Dockerfile
    env_file:
      - project.env
      - .env
    environment:
      - PGHOST=database
      - PGPORT=5432
    volumes:
      - ./apps:/workspace/apps:delegated
      - ./utils:/workspace/utils:delegated
      - ./scripts:/workspace/scripts:delegated
      - ./data:/workspace/data:delegated
      - ./app_loader.py:/workspace/app_loader.py:ro
      - ./pipeline.py:/workspace/pipeline.py:ro
      - *hf-cache
      # uncomment the next line to mount the entire workspace (including your host .venv)
      # - .:/workspace:delegated
    ports:
      - 7860:7860
    depends_on:
      - database
    profiles:
      - ui

  query:
    build:
      context: .
      dockerfile: apps/query/Dockerfile
    env_file:
      - project.env
      - .env
    environment:
      - PGHOST=database
      - PGPORT=5432
    volumes:
      - ./apps:/workspace/apps:delegated
      - ./utils:/workspace/utils:delegated
      - ./scripts:/workspace/scripts:delegated
      - ./data:/workspace/data:delegated
      - ./app_query.py:/workspace/app_query.py:ro
      - ./pipeline.py:/workspace/pipeline.py:ro
      - *hf-cache
      # uncomment the next line to mount the entire workspace (including your host .venv)
      # - .:/workspace:delegated
    ports:
      - 7861:7860
    depends_on:
      - database
    profiles:
      - ui

volumes:
  pgdata:

